### ISSUE TITLE
Push to Production

### ISSUE THREAD

**Issue by benbalter** [presidential-innovation-fellows/apidocs#7]
Moved the documentation from staging to production in a57776167d8c73a21f54e44637a6a044d5f955b9, and would love if apidocs.presidentialinnovationfellows.org could reflect the change? Not sure how things work.

Thanks! :camel: :cactus: :ship: :bug: :pager:

**Comment by ajb** [comment]
I'll deploy for now, it's just a git push to ec2. Contact me on chat if you
want me to add your key and help you set up the remote?

On Wed, Feb 27, 2013 at 9:12 AM, Benjamin J. Balter <
notifications@github.com> wrote:

> Moved the documentation from staging to production in a577761https://github.com/presidential-innovation-fellows/apidocs/commit/a57776167d8c73a21f54e44637a6a044d5f955b9,
> and would love if apidocs.presidentialinnovationfellows.org could reflect
> the change? Not sure how things work.
> 
> Thanks! [image: :camel:][image: :cactus:][image: :ship:][image: :bug:][image:
> :pager:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/presidential-innovation-fellows/apidocs/issues/7
> .

## 

Adam Becker | Project RFP-EZ http://wh.gov/innovationfellows/rfpez |
510.928.9111
| Adam.Becker@sba.gov

**Comment by ajb** [comment]
lol

**Comment by ajb** [comment]
p.s. i wonder where this site lives now...
